version: "3.9"

services:
  work:
    image: rusconn/postgres-sample-work:1.0.0
    build:
      context: .devcontainer
    working_dir: /work
    volumes:
      - .:/work:cached
    depends_on:
      - db
    tty: true
